# Assignment For Numpy

---
## **Assignment # 02**
### **Topic:** Numerical Python (Numpy Fundamentals)
##### **Name:** Syed Huzaifa.
##### **Roll Num:** PIAIC166759
##### **Batch:** 35
##### **Course:** Artificial Intelligence (AI)
---

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("THIS IS THE ARRAY 1D AFTER CONVERION INTO 2D ARRAY WITH TWO ROWS:")
print("=================================================================")
arr1.reshape(2,5)

THIS IS THE ARRAY 1D AFTER CONVERION INTO 2D ARRAY WITH TWO ROWS:


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [18]:
a = np.arange(0,10).reshape(2,5)
b = np.ones((2,5),dtype=int).reshape(2,5)
print("THIS IS THE OUTPUT AFTER STACKING THE TWO ARRAYS VERTICALLY:")
print("=============================================================")
np.vstack((a,b))

THIS IS THE OUTPUT AFTER STACKING THE TWO ARRAYS VERTICALLY:


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [19]:
a = np.arange(0,10).reshape(2,5)
b = np.ones((2,5),dtype=int).reshape(2,5)
print("THIS IS THE OUTPUT AFTER STACKING THE TWO ARRAYS HORIZONTALLY:")
print("=============================================================")
np.hstack((a,b))

THIS IS THE OUTPUT AFTER STACKING THE TWO ARRAYS HORIZONTALLY:


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [36]:
a = np.array([0,1,2,3,4,5,6,7,8,9,]).reshape(5,2)
print("THIS IS THE 1D ARRAY AFTER FLATTENING THE ARRAY OF SHAPE '5,2':")
print("===============================================================")
np.ravel(a)

THIS IS THE 1D ARRAY AFTER FLATTENING THE ARRAY OF SHAPE '5,2':


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [51]:
a = np.arange(0,15).reshape(5,3)
print("THIS IS THE HIGHER DIMENSION ARRAY AFTER CONVERSION INTO 1D:")
print("============================================================")
a.ra(1,15)

THIS IS THE HIGHER DIMENSION ARRAY AFTER CONVERSION INTO 1D:


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [2]:
a = np.arange(0,15)
print("THIS IS THE 1D ARRAY AFTER CONVERSION INTO HIGHER DIMENSION:")
print("============================================================")
a.ravel()

THIS IS THE 1D ARRAY AFTER CONVERSION INTO HIGHER DIMENSION:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:7

### Create 5x5 an array and find the square of an array?

In [3]:
a = np.arange(2,27).reshape(5,5)
print("THIS IS THE ARRAY CONTAINING THE SQUARES OF THE ELEMENTS OF ARRAY 'a':")
print("======================================================================")
np.square(a)

THIS IS THE ARRAY CONTAINING THE SQUARES OF THE ELEMENTS OF ARRAY 'a':


array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [70]:
a = np.random.randn(5,6)
print("THIS IS THE MEAN OF THE ARRAY 'a':")
print("==================================")
a.mean()

THIS IS THE MEAN OF THE ARRAY 'a':


0.20655161961365345

## Question:9

### Find the standard deviation of the previous array in Q8?

In [71]:
print("THIS IS THE STANDARD DEVIATION OF THE ARRAY 'a':")
print("================================================")
a.std()

THIS IS THE STANDARD DEVIATION OF THE ARRAY 'a':


1.0824961279709069

## Question:10

### Find the median of the previous array in Q8?

In [72]:
print("THIS IS THE MEDIAN OF THE ARRAY 'a':")
print("====================================")
np.median(a)

THIS IS THE MEDIAN OF THE ARRAY 'a':


0.23528026694048704

## Question:11

### Find the transpose of the previous array in Q8?

In [75]:
print("THIS IS THE TRANSPOSE OF THE ARRAY 'a':")
print("=======================================")
a.transpose()

THIS IS THE TRANSPOSE OF THE ARRAY 'a':


array([[ 0.23049288,  0.74473163, -0.21237738,  0.49355777,  0.25347832],
       [ 0.46930891, -0.75300761, -0.01526924,  0.60791865,  1.12849936],
       [-0.44710295,  0.84382469,  2.49807174,  0.47213811, -1.11189159],
       [-2.15679632, -0.50540482,  0.24006765,  0.89987262, -1.08603055],
       [-0.88211761,  1.01059308,  0.06611107,  0.06972766,  2.38770139],
       [ 0.03495288, -1.80710653, -0.68742413,  2.15978281,  1.2502461 ]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [78]:
b = np.random.randn(4,4)
print("THIS IS THE SUM OF THE DIAGONAL ELEMENTS OF THE ARRAY 'b':")
print("==========================================================")
b.diagonal()

THIS IS THE SUM OF THE DIAGONAL ELEMENTS OF THE ARRAY 'b':


array([ 1.41547325,  0.36958776, -0.31795167,  0.73212312])

## Question:13

### Find the determinant of the previous array in Q12?

In [83]:
print("THIS IS DETERMINANT OF THE ARRAY 'b':")
print("=========================================")
np.linalg.det(b)

THIS IS DETERMINANT OF THE ARRAY 'b':


0.46485688410458675

## Question:14

### Find the 5th and 95th percentile of an array?

In [91]:
c = np.arange(100).reshape(20,5)
print("THIS IS THE 5th PERCENTILE OF ARRAY 'c': ")
print("=========================================")
np.percentile (c, 5, axis=None, out=None)

THIS IS THE 5th PERCENTILE OF ARRAY 'c': 


4.95

In [92]:
c = np.arange(100).reshape(20,5)
print("THIS IS THE 95th PERCENTILE OF ARRAY 'c': ")
print("==========================================")
np.percentile (c, 95, axis=None, out=None)

THIS IS THE 95th PERCENTILE OF ARRAY 'c': 


94.05

## Question:15

### How to find if a given array has any null values?

In [7]:
a = np.array([120,50,5,np.NaN,25,68,34,0,80,np.NaN])
print("THIS IS THE ARRAY OBTAINED AFTER CHECKING FOR NULL VALUES. 'FALSE' INDICATES THE RIGHT VALUE WHILE 'TRUE' INDICATES THE 'null' VALUE:")
print("============================================================================================================================")
np.isnan(a)

THIS IS THE ARRAY OBTAINED AFTER CHECKING FOR NULL VALUES. 'FALSE' INDICATES THE RIGHT VALUE WHILE 'TRUE' INDICATES THE 'null' VALUE:


array([False, False, False,  True, False, False, False, False, False,
        True])